#!/bin/sh
#
# cphipps - short script to start building from a maintainer-clean'ed tree
#
mkdir -p autotools
aclocal19 -I autotools && autoheader259 && automake19 --add-missing --foreign && autoconf259
