#!/bin/sh -e

${top_builddir-.}/zsyncmake -u foo -f foo ${srcdir-.}/INSTALL

# Note TAB required for Solaris cksum
x=`sed -e '1s/0\.6/XXX/' foo.zsync | cksum | sed -e 's/[ 	][0-9].*//'`
[ $x = 1368366867 ]
rm foo.zsync

