#!/bin/sh -ex

#alias sha1sum=sha1
PATH="/home/cph/src/zsync/main/c:$PATH"
ls -l `which zsync`
zsync -V
#OPTS="-A localhost=cph:foobar"

testnums=${1-"1 2 3 4 5 6 7 8 9 11 12 13 14 20 21"}

for i in $testnums
do
	old="$i/old"
	[ -f $old ] || old="$i/old.gz"
	rm -f get*
	wc -c $i/get.zsync
	time zsync $OPTS -i $old 'http://localhost:2000/'/ztest/$i/get.zsync
	if [ -f get.gz ]
	then
		cmp get.gz $i/new
	else
		sha1sum get
	fi
done
